apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-mgr
  namespace: ahsoka3
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - create
  - watch
  - list
